# Generated by Django 4.1.3 on 2023-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='None.jpg', upload_to='media'),
        ),
    ]
