# Generated by Django 4.1.3 on 2023-02-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0007_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
